products:
  go-license:
    build:
      main-pkg: .
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
      version-var: github.com/palantir/go-generate/vendor/github.com/palantir/pkg/cobracli.Version
  license-plugin:
    build:
      main-pkg: ./godelplugin
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
      version-var: github.com/palantir/go-generate/vendor/github.com/palantir/pkg/cobracli.Version
group-id: com.palantir.godel
